import { useEffect, useRef } from 'react';
import L from 'leaflet';
import { Expand, MapPinned } from 'lucide-react';
import type { Officer, Settings, Location } from '../types';
import { labels, time, trackingState } from '../lib/format';

export function LiveMap({ officers, settings, now, selected, select, route }: { officers: Officer[]; settings: Settings; now: number; selected: string | null; select(id: string): void; route?: Location[] }) {
  const node = useRef<HTMLDivElement>(null), map = useRef<L.Map | null>(null), markers = useRef(new Map<string, L.Marker>()), line = useRef<L.Polyline | null>(null);
  useEffect(() => { if (!node.current || map.current) return; map.current = L.map(node.current).setView([32.93, 72.85], 9); L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 19, attribution: '&copy; OpenStreetMap contributors' }).addTo(map.current); return () => { map.current?.remove(); map.current = null; }; }, []);
  useEffect(() => { if (!map.current) return; const active = new Set<string>(); for (const row of officers) { if (row.session?.status !== 'ACTIVE' || !row.lastLocation) continue; const p = row.lastLocation, state = trackingState(row, settings, now); active.add(row.fmo.id); const icon = L.divIcon({ className: 'leaflet-fmo-pin ' + (state === 'TRACKING' ? 'is-live' : 'is-stale'), html: `<span>${row.fmo.employeeCode.split('-').at(-1) ?? 'FMO'}</span>`, iconSize: [34, 34], iconAnchor: [17, 34] }); const popup = `<strong>${row.fmo.name}</strong><br>${row.fmo.employeeCode}<br>${labels[state] ?? state}<br>Last update: ${time(p.recordedAt, settings.timezone, true)}<br>Accuracy: ${Math.round(p.accuracy)}m`; let marker = markers.current.get(row.fmo.id); if (!marker) { marker = L.marker([p.latitude, p.longitude], { icon }).addTo(map.current).on('click', () => select(row.fmo.id)); markers.current.set(row.fmo.id, marker); } else marker.setLatLng([p.latitude, p.longitude]).setIcon(icon); marker.bindPopup(popup); if (selected === row.fmo.id) marker.openPopup(); } for (const [id, marker] of markers.current) if (!active.has(id)) { marker.remove(); markers.current.delete(id); } const points = route?.map(p => [p.latitude, p.longitude] as [number, number]) ?? []; line.current?.remove(); line.current = points.length > 1 ? L.polyline(points, { color: '#087f68', weight: 4 }).addTo(map.current) : null; }, [officers, settings, now, selected, select, route]);
  function fit() { if (!map.current) return; const group = L.featureGroup([...markers.current.values()]); if (group.getLayers().length) map.current.fitBounds(group.getBounds().pad(.2)); else if (route?.length) map.current.fitBounds(L.latLngBounds(route.map(p => [p.latitude, p.longitude] as [number, number])).pad(.2)); }
  return <div className="map-shell"><div ref={node} className="map-canvas" aria-label="OpenStreetMap of active FMO locations" /><button className="button map-fit" onClick={fit}><Expand size={16} />Fit map</button><div className="map-legend"><span><i className="dot green" />Recent</span><span><i className="dot grey" />Stale / offline</span><span><i className="dot amber" />GPS needs review</span></div>{!officers.some(o => o.lastLocation) && <div className="map-empty"><MapPinned size={30} /><p>Waiting for real device location updates.</p></div>}</div>;
}
