import { useEffect, useState, useSyncExternalStore, type FormEvent } from 'react';
import { LayoutDashboard, MapPinned, Users, ClipboardCheck, LogOut, ArrowRight, ShieldCheck, Radio, Menu, PanelLeftClose } from 'lucide-react';
import { authSnapshot, login, logout, refreshSession, subscribeAuth } from './lib/auth';
import { useOperations } from './lib/useOperations';
import { ago } from './lib/format';
import { Overview } from './pages/Overview';
import { Officers } from './pages/Officers';
import { Attendance } from './pages/Attendance';
import { History } from './pages/History';
import { Reports } from './pages/Reports';
import { Settings } from './pages/Settings';
import { ErrorNotice } from './components/ui';

export default function App() {
  useEffect(() => {
    let lastActivity = Date.now();
    const markActive = () => { lastActivity = Date.now(); };
    const events = ['pointerdown', 'keydown', 'scroll', 'mousemove', 'touchstart'];
    events.forEach(event => window.addEventListener(event, markActive, { passive: true }));
    const timer = window.setInterval(() => { if (Date.now() - lastActivity >= 120000) window.location.reload(); }, 60000);
    return () => { window.clearInterval(timer); events.forEach(event => window.removeEventListener(event, markActive)); };
  }, []);
  const session = useSyncExternalStore(subscribeAuth, authSnapshot), [booting, setBooting] = useState(true), [error, setError] = useState('');
  useEffect(() => { void refreshSession().catch(() => undefined).finally(() => setBooting(false)); }, []);
  if (booting) return <div className="boot"><div className="brand-mark"><MapPinned size={28} /></div><p>Opening field operations…</p></div>;
  if (!session) return <Login externalError={error} clearError={() => setError('')} />;
  return <Dashboard key={session.user.id} name={session.user.name} role={session.user.role} demo={session.user.isDemo} signOut={() => { void logout().catch(failure => setError(failure instanceof Error ? failure.message : 'Sign-out could not be confirmed.')); }} />;
}
function Login({ externalError, clearError }: { externalError: string; clearError(): void }) {
  const [employee, setEmployee] = useState(''), [password, setPassword] = useState(''), [remember, setRemember] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState('');
  async function submit(event: FormEvent) { event.preventDefault(); if (busy) return; setBusy(true); setError(''); clearError(); try { await login(employee.trim(), password, remember); setPassword(''); } catch (failure) { setError(failure instanceof Error ? failure.message : 'Unable to sign in.'); } finally { setBusy(false); } }
  return <div className="login-layout"><section className="login-story"><div className="brand"><span className="brand-mark"><MapPinned size={24} /></span><div>FIELD OPERATIONS<small>FMO COMMAND CENTER</small></div></div><div className="login-message"><span className="eyebrow">A CLEARER VIEW OF THE FIELD</span><h1>Connected teams.<br />Accountable operations.</h1><p>Attendance, duty status and live field locations, together in one secure workspace.</p><div className="story-features"><span><Radio size={18} />Live duty visibility</span><span><ClipboardCheck size={18} />Confirmed attendance records</span><span><ShieldCheck size={18} />Private evidence access</span></div></div><footer>Built for the people who keep your city moving.</footer></section><main className="login-form-panel"><div className="login-form"><span className="login-label">ADMINISTRATOR ACCESS</span><h2>Welcome back.</h2><p>Sign in to your operations workspace.</p><form onSubmit={event => void submit(event)}><ErrorNotice message={error || externalError} /><label>Employee / admin ID<input autoComplete="username" required value={employee} onChange={event => setEmployee(event.target.value)} placeholder="Enter your employee ID" maxLength={80} /></label><label>Password<input autoComplete="current-password" type="password" required value={password} onChange={event => setPassword(event.target.value)} placeholder="Enter your password" /></label><label className="checkbox-label"><input type="checkbox" checked={remember} onChange={event => setRemember(event.target.checked)} />Remember me</label><button className="button primary" disabled={busy}>{busy ? 'Signing in…' : 'Sign in to dashboard'}<ArrowRight size={18} /></button></form><div className="login-security"><ShieldCheck size={17} /><p>Authorized personnel only. FMOs use the Android application to start duty and check in.</p></div></div><small className="login-copyright">FMO Attendance & Live Tracking</small></main></div>;
}
const navigation = [{ id: 'overview', label: 'Overview', icon: LayoutDashboard }, { id: 'tracking', label: 'Live tracking', icon: MapPinned }, { id: 'officers', label: 'Field officers', icon: Users }, { id: 'attendance', label: 'Attendance', icon: ClipboardCheck }, { id: 'history', label: 'Route history', icon: MapPinned }, { id: 'reports', label: 'Reports', icon: ClipboardCheck }, { id: 'settings', label: 'Settings', icon: ShieldCheck }];
function Dashboard({ name, role, demo, signOut }: { name: string; role: string; demo: boolean; signOut(): void }) {
  const [page, setPage] = useState(() => navigation.some(item => item.id === location.hash.slice(1)) ? location.hash.slice(1) : 'overview'), [menu, setMenu] = useState(false); const operations = useOperations();
  useEffect(() => { const update = () => setPage(navigation.some(item => item.id === location.hash.slice(1)) ? location.hash.slice(1) : 'overview'); window.addEventListener('hashchange', update); return () => window.removeEventListener('hashchange', update); }, []);
  return <div className="dashboard-layout"><aside className={'sidebar ' + (menu ? 'open' : '')}><a className="brand" href="#overview"><span className="brand-mark"><MapPinned size={24} /></span><div>FIELD OPERATIONS<small>FMO COMMAND CENTER</small></div></a><span className="nav-label">WORKSPACE</span><nav aria-label="Main navigation">{navigation.map(item => <a key={item.id} href={'#' + item.id} className={page === item.id ? 'active' : ''} onClick={() => setMenu(false)}><item.icon size={19} />{item.label}{item.id === 'tracking' && <i className="live-dot" />}</a>)}</nav><div className="sidebar-bottom"><div className="duty-notice"><ShieldCheck size={20} /><strong>Duty-bound. Always visible.</strong><p>Locations are recorded during authorized FMO duty sessions.</p></div><div className="account"><span className="avatar">{name.split(' ').map(part => part[0]).slice(0, 2).join('')}</span><div><strong>{name}</strong><small>{demo ? 'DEMO · ' : ''}{role.replaceAll('_', ' ')}</small></div><button onClick={signOut} className="text-button" aria-label="Sign out"><LogOut size={17} /> Logout</button></div></div></aside><div className="workspace"><header className="topbar"><div className="breadcrumb"><button className="icon-button mobile-menu" aria-label="Toggle navigation" onClick={() => setMenu(!menu)}>{menu ? <PanelLeftClose size={21} /> : <Menu size={21} />}</button><span>{operations.settings?.organizationName ?? 'Field Monitoring Organization'}</span><span>/</span><strong>{navigation.find(item => item.id === page)?.label}</strong></div><div className="connection"><i className={'dot ' + (operations.connection === 'Live' ? 'green' : 'amber')} /><span>{operations.connection === 'Live' ? 'Live connection' : operations.connection}</span><small>Synced {ago(operations.updated, operations.now)}</small></div></header><main className="main-content"><ErrorNotice message={operations.error} retry={operations.refresh} />{page === 'overview' || page === 'tracking' ? <Overview operations={operations} full={page === 'tracking'} /> : page === 'officers' ? <Officers settings={operations.settings} changed={operations.refresh} /> : page === 'history' ? <History officers={operations.officers} settings={operations.settings} /> : page === 'reports' ? <Reports settings={operations.settings} /> : page === 'settings' ? <Settings settings={operations.settings} changed={operations.refresh} /> : <Attendance settings={operations.settings} revision={operations.revision} changed={operations.refresh} />}</main><footer className="workspace-footer"><span>FMO / FIELD OPERATIONS</span><span>Private organizational workspace</span></footer></div></div>;
}
