import { useEffect, useState } from 'react';
import { CalendarDays, Eye, ImageOff, ShieldCheck } from 'lucide-react';
import { api, selfie } from '../lib/auth';
import { useQuery } from '../lib/useQuery';
import { dateInZone, duration, time } from '../lib/format';
import type { Attendance as Record, Fmo, Page, Session, Settings } from '../types';
import { Badge, Demo, Empty, ErrorNotice, Modal, Pager } from '../components/ui';

export function Attendance({ settings, revision, changed }: { settings: Settings | null; revision: number; changed(): void }) {
  const timezone = settings?.timezone ?? 'Asia/Karachi'; const [date, setDate] = useState(() => dateInZone(timezone)), [fmoId, setFmoId] = useState(''), [offset, setOffset] = useState(0), [selected, setSelected] = useState<string | null>(null), [officers, setOfficers] = useState<Fmo[]>([]), [filterError, setFilterError] = useState('');
  const records = useQuery<Page<Record>>('/api/attendance?limit=25&offset=' + offset + (date ? '&date=' + date : '') + (fmoId ? '&fmoId=' + fmoId : ''));
  useEffect(() => { let alive = true; void (async () => { const rows: Fmo[] = []; let page: Page<Fmo>, start = 0; do { page = await api<Page<Fmo>>('/api/fmos?limit=100&offset=' + start); rows.push(...page.items); start += 100; } while (page.hasMore && alive); if (alive) setOfficers(rows); })().catch(failure => { if (alive) setFilterError(String(failure)); }); return () => { alive = false; }; }, []);
  useEffect(() => { const timer = setTimeout(() => void records.reload(), 1500); return () => clearTimeout(timer); }, [revision, records.reload]);
  return <><div className="page-heading"><div><div className="eyebrow">ATTENDANCE REGISTER</div><h1>Attendance records</h1><p>Server-confirmed check-ins and private attendance evidence.</p></div><span className="date-chip"><ShieldCheck size={16} />Authenticated evidence access</span></div><section className="panel"><div className="table-toolbar"><label className="filter-label"><CalendarDays size={17} /><span>Check-in date</span><input aria-label="Attendance date" type="date" value={date} onChange={event => { setDate(event.target.value); setOffset(0); }} /></label><label className="filter-label"><span>FMO</span><select aria-label="Filter attendance by FMO" value={fmoId} onChange={event => { setFmoId(event.target.value); setOffset(0); }}><option value="">All officers</option>{officers.map(fmo => <option key={fmo.id} value={fmo.id}>{fmo.employeeCode} · {fmo.name}{fmo.isActive ? '' : ' (inactive)'}</option>)}</select></label><span className="quiet-label">{timezone}</span></div><ErrorNotice message={records.error || filterError} retry={() => void records.reload()} />
    <div className="table-wrap"><table><thead><tr><th>Field officer</th><th>Date / check-in</th><th>Duty start</th><th>Check-in location</th><th>Attendance</th><th>Tracking</th><th>Duty end</th><th>Total duration</th><th>Evidence</th></tr></thead><tbody>{records.data?.items.map(record => <tr key={record.id}><td><strong>{record.name}<Demo show={record.isDemo} /></strong><small>{record.employeeCode}</small></td><td>{time(record.checkInTime, timezone, true)}</td><td>{time(record.dutyStart, timezone)}</td><td><span className="mono">{record.latitude.toFixed(5)}, {record.longitude.toFixed(5)}</span><small>{Math.round(record.accuracy)}m accuracy</small></td><td><Badge value={record.supersededAt ? 'SUPERSEDED' : 'CHECKED_IN'} /></td><td><Badge value={record.trackingStatus ?? 'UNASSESSED'} /></td><td>{time(record.dutyEnd, timezone)}</td><td>{duration(record.serverDurationSeconds)}</td><td><button className="text-button" onClick={() => setSelected(record.id)}><Eye size={16} />View</button></td></tr>)}</tbody></table></div>{!records.data?.items.length && <Empty title={records.busy ? 'Loading attendance…' : 'No attendance for this selection'}>Start Duty alone is not a check-in. Attendance appears after a successful live-selfie submission.</Empty>}<Pager offset={offset} hasMore={records.data?.hasMore ?? false} onPage={setOffset} busy={records.busy} /></section>
    {selected && <AttendanceDetails id={selected} timezone={timezone} close={() => setSelected(null)} changed={() => { void records.reload(); changed(); }} />}
  </>;
}
function AttendanceDetails({ id, timezone, close, changed }: { id: string; timezone: string; close(): void; changed(): void }) {
  const detail = useQuery<{ attendance: Record; session: Session }>('/api/attendance/' + id); const [image, setImage] = useState(''), [imageError, setImageError] = useState(''), [reason, setReason] = useState(''), [resetting, setResetting] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState('');
  useEffect(() => { let alive = true; let url = ''; void selfie(id).then(blob => { if (alive) { url = URL.createObjectURL(blob); setImage(url); } }).catch(failure => { if (alive) setImageError(failure instanceof Error ? failure.message : 'Selfie unavailable.'); }); return () => { alive = false; if (url) URL.revokeObjectURL(url); }; }, [id]);
  const row = detail.data?.attendance, session = detail.data?.session;
  async function reset() { if (busy) return; setBusy(true); try { await api('/api/attendance/' + id + '/reset', 'POST', { reason }); setResetting(false); setReason(''); await detail.reload(); changed(); } catch (failure) { setError(failure instanceof Error ? failure.message : 'Unable to reset attendance.'); } finally { setBusy(false); } }
  return <Modal title="Attendance evidence" close={() => { if (!busy) close(); }} wide><div className="form-body"><ErrorNotice message={detail.error || error} />{row && session ? <><div className="detail-identity"><div><h2>{row.name}<Demo show={row.isDemo} /></h2><p>{row.employeeCode} · {time(row.checkInTime, timezone, true)}</p></div><Badge value={row.supersededAt ? 'SUPERSEDED' : 'CHECKED_IN'} /></div><div className="evidence-grid"><div className="selfie-view">{image ? <img src={image} alt={'Private check-in selfie for ' + row.name} /> : <div className="empty"><ImageOff size={34} /><p>{imageError || 'Loading private selfie…'}</p></div>}<span><ShieldCheck size={14} />Private attendance evidence</span></div><div className="evidence-facts"><div><label>Check-in coordinates</label><strong className="mono">{row.latitude.toFixed(6)}, {row.longitude.toFixed(6)}</strong></div><div><label>GPS accuracy</label><strong>{Math.round(row.accuracy)} meters</strong></div><div><label>Duty start / expected end</label><strong>{time(session.startTime, timezone)} / {time(session.expectedEndTime, timezone)}</strong></div><div><label>Server end / duration</label><strong>{time(session.actualEndTime, timezone)} / {duration(session.serverDurationSeconds)}</strong></div>{session.reportedStopTime && <div><label>Device-reported stop (unverified)</label><strong>{time(session.reportedStopTime, timezone, true)} · {duration(session.reportedDurationSeconds)}</strong></div>}<div><label>Identity verification</label><strong>{row.verificationStatus.replaceAll('_', ' ')}</strong><small>Camera capture is not biometric or liveness verification.</small></div>{session.endLocationFailure && <p className="warning-note">Final GPS: {session.endLocationFailure.replaceAll('_', ' ')}</p>}</div></div>{row.supersededAt && <p className="warning-note">Superseded: {row.resetReason}. Original evidence is preserved.</p>}
      {session.status === 'ACTIVE' && !row.supersededAt && <div className="reset-area">{resetting ? <><label>Reason for resetting attendance<textarea required minLength={5} maxLength={500} value={reason} onChange={event => setReason(event.target.value)} /></label><p className="muted">Original evidence is retained. The FMO must take a new selfie. This action is audited.</p><button className="button danger" disabled={busy || reason.trim().length < 5} onClick={() => void reset()}>{busy ? 'Resetting…' : 'Confirm attendance reset'}</button><button className="button subtle" disabled={busy} onClick={() => setResetting(false)}>Cancel</button></> : <button className="text-button" onClick={() => setResetting(true)}>Reset attendance with a reason</button>}</div>}
    </> : <Empty title="Loading attendance details…" />}</div></Modal>;
}
