import { useEffect, useState } from 'react';
import { api } from '../lib/auth';
import { chronological } from '../lib/history';
import { dateInZone, time } from '../lib/format';
import { LiveMap } from '../components/LiveMap';
import { Empty, ErrorNotice } from '../components/ui';
import type { Officer, Fmo, Session, Location, Settings, Page } from '../types';
export function History({ officers, settings }: { officers: Officer[]; settings: Settings | null }) {
  const [choices, setChoices] = useState<Fmo[]>(() => officers.map(row => row.fmo));
  const [fmoId, setFmo] = useState(''), [date, setDate] = useState(() => dateInZone(settings?.timezone ?? 'Asia/Karachi')), [sessions, setSessions] = useState<Session[]>([]), [sessionId, setSession] = useState(''), [points, setPoints] = useState<Location[]>([]), [busy, setBusy] = useState(false), [error, setError] = useState('');
  useEffect(() => { let alive = true; void (async () => { const all: Fmo[] = []; let page: Page<Fmo>, offset = 0; do { page = await api<Page<Fmo>>('/api/fmos?limit=100&offset=' + offset); all.push(...page.items); offset += 100; } while (alive && page.hasMore); if (alive) setChoices(all); })().catch(failure => { if (alive) setError(String(failure)); }); return () => { alive = false; }; }, []);
  useEffect(() => { let alive = true; setSessions([]); setSession(''); setPoints([]); setError(''); if (!fmoId) return;
    void (async () => { const all: Session[] = []; let page: Page<Session>, offset = 0; do { page = await api<Page<Session>>('/api/fmos/' + fmoId + '/sessions?limit=100&offset=' + offset + (date ? '&date=' + date : '')); all.push(...page.items); offset += 100; } while (alive && page.hasMore); if (alive) { setSessions(all); setSession(all[0]?.id ?? ''); } })().catch(failure => { if (alive) setError(String(failure)); }); return () => { alive = false; };
  }, [fmoId, date]);
  useEffect(() => { let alive = true; setPoints([]); if (!sessionId) { setBusy(false); return; } setBusy(true); setError('');
    void (async () => { const all: Location[] = []; let cursor = '0'; let more = true; while (alive && more) { const page = await api<{ points: Location[]; hasMore: boolean; nextAfterId: string }>('/api/fmos/' + fmoId + '/route?dutySessionId=' + sessionId + '&limit=2000&afterId=' + cursor); if (page.hasMore && BigInt(page.nextAfterId) <= BigInt(cursor)) throw new Error('Route pagination did not advance.'); all.push(...page.points); more = page.hasMore; cursor = page.nextAfterId; } if (alive) setPoints(chronological(all)); })().catch(failure => { if (alive) setError(String(failure)); }).finally(() => { if (alive) setBusy(false); }); return () => { alive = false; };
  }, [fmoId, sessionId]);
  if (!settings) return <Empty title="Loading settings…" />;
  return <><div className="page-heading"><div><div className="eyebrow">MOVEMENT HISTORY</div><h1>Route history</h1><p>Complete session observations, ordered by collection time.</p></div></div><section className="panel"><div className="table-toolbar"><label className="filter-label">Officer<select value={fmoId} onChange={event => setFmo(event.target.value)}><option value="">Select officer</option>{choices.map(fmo => <option key={fmo.id} value={fmo.id}>{fmo.employeeCode} · {fmo.name}</option>)}</select></label><label className="filter-label">Duty start date<input type="date" value={date} onChange={event => setDate(event.target.value)} /></label><label className="filter-label">Session<select value={sessionId} onChange={event => setSession(event.target.value)}><option value="">Select session</option>{sessions.map(session => <option key={session.id} value={session.id}>{time(session.startTime, settings.timezone, true)} · {session.status}</option>)}</select></label></div><ErrorNotice message={error} />{busy ? <Empty title="Loading complete route…">Fetching every page; no points are silently truncated.</Empty> : <LiveMap officers={[]} settings={settings} now={Date.now()} selected={null} select={() => undefined} route={points} />}<div className="panel-heading"><div><h2>{points.length} recorded observations</h2><p>{points.length ? time(points[0]!.recordedAt, settings.timezone, true) + ' — ' + time(points.at(-1)!.recordedAt, settings.timezone, true) : 'Choose an officer and duty session.'}</p></div><span className="quiet-label">{points.filter(point => point.quality === 'POOR' || point.mocked).length} poor / mock readings retained</span></div><p className="muted" style={{ padding: 20 }}>A polyline connects observations, not a verified road route. GPS gaps and inaccurate readings can produce straight-line jumps. An active route is a snapshot; reselect the session to include later uploads.</p></section></>;
}
