import { useState, type FormEvent } from 'react';
import { Plus, Search, Pencil, UserRound, Phone, Mail } from 'lucide-react';
import type { Fmo, Officer, Page, Settings } from '../types';
import { api } from '../lib/auth';
import { useQuery } from '../lib/useQuery';
import { Badge, Demo, Empty, ErrorNotice, Modal, Pager } from '../components/ui';
import { time } from '../lib/format';

export function Officers({ settings, changed }: { settings: Settings | null; changed(): void }) {
  const [search, setSearch] = useState(''), [query, setQuery] = useState(''), [offset, setOffset] = useState(0), [editing, setEditing] = useState<Fmo | 'new' | null>(null), [detail, setDetail] = useState<string | null>(null);
  const records = useQuery<Page<Fmo>>('/api/fmos?limit=25&offset=' + offset + '&search=' + encodeURIComponent(query));
  return <><div className="page-heading"><div><div className="eyebrow">PEOPLE & ASSIGNMENTS</div><h1>Field officers</h1><p>Manage your team and access individual duty records.</p></div><button className="button primary" onClick={() => setEditing('new')}><Plus size={17} />Add FMO</button></div>
    <section className="panel"><form className="table-toolbar" onSubmit={event => { event.preventDefault(); setOffset(0); setQuery(search.trim()); }}><label className="search"><Search size={18} /><input aria-label="Search FMOs" placeholder="Search by name or employee ID" value={search} maxLength={100} onChange={event => setSearch(event.target.value)} /></label><button className="button subtle" type="submit">Search officers</button></form><ErrorNotice message={records.error} retry={() => void records.reload()} />
      <div className="table-wrap"><table><thead><tr><th>Field officer</th><th>Employee ID</th><th>Contact</th><th>Account status</th><th>Actions</th></tr></thead><tbody>{records.data?.items.map(fmo => <tr key={fmo.id}><td><button className="person-cell" onClick={() => setDetail(fmo.id)}><span className="avatar"><UserRound size={18} /></span><strong>{fmo.name}<Demo show={fmo.isDemo} /></strong></button></td><td className="mono">{fmo.employeeCode}</td><td><div>{fmo.phone || '—'}</div><small>{fmo.email || 'No email provided'}</small></td><td><Badge value={fmo.isActive ? 'ACTIVE' : 'INACTIVE'} /></td><td><div className="table-actions"><button className="text-button" onClick={() => setDetail(fmo.id)}>View details</button><button className="icon-button" aria-label={'Edit ' + fmo.name} onClick={() => setEditing(fmo)}><Pencil size={16} /></button></div></td></tr>)}</tbody></table></div>
      {!records.data?.items.length && <Empty title={records.busy ? 'Loading officers…' : 'No matching officers'}>Add an FMO or adjust the search.</Empty>}<Pager offset={offset} hasMore={records.data?.hasMore ?? false} onPage={setOffset} busy={records.busy} />
    </section>
    {editing && <FmoEditor key={typeof editing === 'string' ? editing : editing.id} fmo={editing} close={() => setEditing(null)} saved={() => { setEditing(null); void records.reload(); changed(); }} />}
    {detail && <FmoDetails id={detail} settings={settings} close={() => setDetail(null)} />}
  </>;
}
function FmoEditor({ fmo, close, saved }: { fmo: Fmo | 'new'; close(): void; saved(): void }) {
  const current = fmo === 'new' ? null : fmo; const [name, setName] = useState(current?.name ?? ''), [employeeCode, setCode] = useState(current?.employeeCode ?? ''), [phone, setPhone] = useState(current?.phone ?? ''), [email, setEmail] = useState(current?.email ?? ''), [password, setPassword] = useState(''), [active, setActive] = useState(current?.isActive ?? true), [busy, setBusy] = useState(false), [error, setError] = useState('');
  async function submit(event: FormEvent) {
    event.preventDefault(); if (busy) return; setBusy(true); setError('');
    try { const body = { name, phone: phone || null, email: email || null, ...(password ? { password } : {}) };
      if (current) await api('/api/fmos/' + current.id, 'PATCH', { ...body, isActive: active }); else await api('/api/fmos', 'POST', { ...body, employeeCode, password });
      setPassword(''); saved();
    } catch (failure) { setError(failure instanceof Error ? failure.message : 'Unable to save officer.'); } finally { setBusy(false); }
  }
  return <Modal title={current ? 'Edit field officer' : 'Add field officer'} close={() => { if (!busy) close(); }}><form className="form-body" onSubmit={event => void submit(event)}><p className="muted">{current ? 'Changes are recorded in the administrative audit log.' : 'Create an account for the FMO Android application.'}</p><ErrorNotice message={error} /><div className="form-grid"><label>Full name<input required maxLength={150} value={name} onChange={event => setName(event.target.value)} autoComplete="name" /></label><label>Employee / FMO ID<input required disabled={!!current} maxLength={80} pattern="[A-Za-z0-9][A-Za-z0-9-]{2,79}" value={employeeCode} onChange={event => setCode(event.target.value.toUpperCase())} placeholder="CHK-FMO-006" /></label><label>Phone<input maxLength={40} type="tel" value={phone} onChange={event => setPhone(event.target.value)} /></label><label>Email<input maxLength={254} type="email" value={email} onChange={event => setEmail(event.target.value)} /></label></div><label>{current ? 'New password (optional)' : 'Initial password'}<input type="password" minLength={12} maxLength={1024} required={!current} value={password} onChange={event => setPassword(event.target.value)} autoComplete="new-password" /><small>At least 12 characters. Password changes revoke existing sessions.</small></label>{current && <label className="checkbox-label"><input type="checkbox" checked={active} onChange={event => setActive(event.target.checked)} />Account active</label>}{current && !active && <p className="warning-note">Deactivation requires the FMO to end any active duty first. Existing sessions will be revoked.</p>}<div className="modal-actions"><button type="button" className="button subtle" disabled={busy} onClick={close}>Cancel</button><button className="button primary" disabled={busy}>{busy ? 'Saving…' : current ? 'Save changes' : 'Create FMO'}</button></div></form></Modal>;
}
function FmoDetails({ id, settings, close }: { id: string; settings: Settings | null; close(): void }) {
  const record = useQuery<Officer>('/api/fmos/' + id); const row = record.data; const timezone = settings?.timezone ?? 'Asia/Karachi';
  return <Modal title="Officer details" close={close}><div className="form-body"><ErrorNotice message={record.error} retry={() => void record.reload()} />{row ? <><div className="detail-identity"><span className="avatar large"><UserRound size={28} /></span><div><h2>{row.fmo.name}<Demo show={row.fmo.isDemo} /></h2><p>{row.fmo.employeeCode}</p></div></div><div className="contact-line"><Phone size={16} />{row.fmo.phone || 'No phone'}<Mail size={16} />{row.fmo.email || 'No email'}</div><div className="detail-grid"><div><label>Duty status</label><Badge value={row.status.duty} /></div><div><label>Tracking</label><Badge value={row.status.tracking} /></div><div><label>Duty start</label><strong>{time(row.session?.startTime, timezone, true)}</strong></div><div><label>Check-in</label><strong>{time(row.attendance?.checkInTime, timezone, true)}</strong></div><div><label>Expected end</label><strong>{time(row.session?.expectedEndTime, timezone, true)}</strong></div><div><label>Last observation</label><strong>{time(row.lastSeen, timezone, true)}</strong></div></div><p className="muted">{row.lastLocation ? 'Last known: ' + row.lastLocation.latitude.toFixed(6) + ', ' + row.lastLocation.longitude.toFixed(6) + ' · ' + Math.round(row.lastLocation.accuracy) + 'm accuracy · ' + row.lastLocation.quality : 'No location has been received.'}</p></> : <Empty title="Loading officer…" />}</div></Modal>;
}
