import { useMemo, useState } from 'react';
import { Users, Radio, CheckCircle2, Clock3, WifiOff, Flag, Search, ArrowUpRight, Navigation, Crosshair } from 'lucide-react';
import type { useOperations } from '../lib/useOperations';
import { ago, time, trackingState } from '../lib/format';
import { Badge, Demo, Empty } from '../components/ui';
import { LiveMap } from '../components/LiveMap';

export function Overview({ operations, full = false }: { operations: ReturnType<typeof useOperations>; full?: boolean }) {
  const { officers, settings, summary, now } = operations; const [search, setSearch] = useState(''), [filter, setFilter] = useState('ACTIVE'), [selected, setSelected] = useState<string | null>(null);
  const rows = useMemo(() => officers.filter(row => (!search || (row.fmo.name + row.fmo.employeeCode).toLowerCase().includes(search.toLowerCase())) && (filter === 'ALL' || filter === 'ACTIVE' ? filter === 'ALL' || row.session?.status === 'ACTIVE' : settings && trackingState(row, settings, now) === filter)).sort((a, b) => a.fmo.employeeCode.localeCompare(b.fmo.employeeCode)), [officers, search, filter, settings, now]);
  const row = officers.find(item => item.fmo.id === selected);
  if (!settings) return <Empty title="Loading field operations">Fetching the latest authorized duty records…</Empty>;
  const onDuty = officers.filter(item => item.session?.status === 'ACTIVE');
  const metrics = [ { name: 'Total FMOs', value: summary?.totalFmos, icon: Users, hint: 'Active employee accounts', color: 'neutral' }, { name: 'On duty', value: onDuty.length, icon: Clock3, hint: 'Duty sessions in progress', color: 'blue' }, { name: 'Checked in', value: onDuty.filter(item => item.attendance).length, icon: CheckCircle2, hint: 'Attendance confirmed', color: 'green' }, { name: 'Currently tracking', value: onDuty.filter(item => trackingState(item, settings, now) === 'TRACKING').length, icon: Radio, hint: 'Recent location received', color: 'green' }, { name: 'Offline', value: onDuty.filter(item => trackingState(item, settings, now) === 'OFFLINE').length, icon: WifiOff, hint: 'No recent GPS observation', color: 'amber' }, { name: 'Completed duty', value: summary?.completedDuty, icon: Flag, hint: 'Officers finished today', color: 'neutral' } ];
  return <>
    <div className="page-heading"><div><div className="eyebrow">FIELD INTELLIGENCE</div><h1>{full ? 'Live tracking' : 'Operations overview'}</h1><p>Your team in the field. One clear picture.</p></div><span className="date-chip">{new Intl.DateTimeFormat('en-GB', { timeZone: settings.timezone, weekday: 'short', day: '2-digit', month: 'long', year: 'numeric' }).format(new Date(now))}</span></div>
    {!full && <div className="metrics">{metrics.map(metric => <article className={'metric metric-' + metric.color} key={metric.name}><div className="metric-top"><span>{metric.name}</span><metric.icon size={18} /></div><strong>{metric.value ?? '—'}</strong><small>{metric.hint}</small></article>)}</div>}
    <section className="panel operations-panel"><div className="panel-heading"><div><h2><span className="live-dot" />Field presence</h2><p>{onDuty.length} officers on duty · {settings.timezone}</p></div><span className="quiet-label">Location updates target {settings.trackingIntervalSeconds}s</span></div>
      <div className="tracking-grid"><div className="map-column"><LiveMap officers={officers} settings={settings} now={now} selected={selected} select={setSelected} /><div className="map-caption"><Navigation size={14} />Locations are device observations. Accuracy and recency vary.</div></div>
        <aside className="officer-list"><div className="list-controls"><label className="search"><Search size={17} /><input aria-label="Search active officers" placeholder="Find an officer…" value={search} onChange={event => setSearch(event.target.value)} /></label><div className="segmented">{[['ACTIVE', 'On duty'], ['OFFLINE', 'Offline'], ['ALL', 'All FMOs']].map(([value, label]) => <button key={value} className={filter === value ? 'selected' : ''} onClick={() => setFilter(value!)}>{label}</button>)}</div></div><div className="officer-scroll">{rows.length ? rows.map(item => <button className={'officer-row ' + (selected === item.fmo.id ? 'selected' : '')} key={item.fmo.id} onClick={() => setSelected(item.fmo.id)}><div className="avatar">{item.fmo.name.split(' ').slice(0, 2).map(part => part[0]).join('')}</div><div className="officer-copy"><strong>{item.fmo.name}<Demo show={item.fmo.isDemo} /></strong><span>{item.fmo.employeeCode}</span><Badge value={trackingState(item, settings, now)} /></div><div className="officer-time"><ArrowUpRight size={15} /><span>{ago(item.lastSeen, now)}</span></div></button>) : <Empty title="No officers in this view">Duty and location updates will appear here as they arrive.</Empty>}</div><div className="list-footer">{rows.length} officers shown · Updated automatically</div></aside>
      </div>
    </section>
    {row && <section className="panel selected-detail"><div className="detail-identity"><Crosshair size={22} /><div><h2>{row.fmo.name} <Demo show={row.fmo.isDemo} /></h2><p>{row.fmo.employeeCode}</p></div><Badge value={row.status.duty} /></div><div className="detail-grid"><div><label>Duty start</label><strong>{time(row.session?.startTime, settings.timezone)}</strong></div><div><label>Check-in</label><strong>{time(row.attendance?.checkInTime, settings.timezone)}</strong></div><div><label>Last update</label><strong>{ago(row.lastSeen, now)}</strong></div><div><label>GPS accuracy</label><strong>{row.lastLocation ? Math.round(row.lastLocation.accuracy) + 'm · ' + row.lastLocation.quality : 'No observation'}</strong></div><div><label>Last known coordinates</label><strong>{row.lastLocation ? row.lastLocation.latitude.toFixed(6) + ', ' + row.lastLocation.longitude.toFixed(6) : '—'}</strong></div></div>{row.session?.status !== 'ACTIVE' && <p className="muted">Retained last-known position. Only active duties are displayed on the live map.</p>}</section>}
    <div className="privacy-footer"><span><span className="live-dot" /> Authorized duty tracking</span><p>Tracking freshness and attendance are separate. “Offline” means no recent location, not proof of a network outage.</p></div>
  </>;
}
