import { useState } from 'react';
import { Download } from 'lucide-react';
import { api } from '../lib/auth';
import { useQuery } from '../lib/useQuery';
import { dateInZone, duration, time } from '../lib/format';
import { downloadCsv } from '../lib/history';
import { Badge, Demo, Empty, ErrorNotice, Pager } from '../components/ui';
import type { Settings, Page } from '../types';
type Row = { fmoId: string; employeeCode: string; name: string; isDemo: boolean; dutySessionId: string | null; startTime: string | null; checkInTime: string | null; actualEndTime: string | null; reportedStopTime: string | null; serverDurationSeconds: number | null; reportedDurationSeconds: number | null; lastSeen: string | null; accuracy: number | null; status: { duty: string; tracking: string } };
export function Reports({ settings }: { settings: Settings | null }) {
  const timezone = settings?.timezone ?? 'Asia/Karachi'; const [date, setDate] = useState(() => dateInZone(timezone)), [offset, setOffset] = useState(0), [exporting, setExporting] = useState(false), [error, setError] = useState('');
  const path = '/api/reports/daily?date=' + date; const records = useQuery<Page<Row>>(path + '&limit=25&offset=' + offset);
  async function exportAll() { setExporting(true); setError(''); try { const all: Row[] = []; let page: Page<Row>, start = 0; do { page = await api<Page<Row>>(path + '&limit=100&offset=' + start); all.push(...page.items); start += 100; } while (page.hasMore); downloadCsv('fmo-duty-' + date + '.csv', [['FMO ID', 'Name', 'Demo', 'Duty session', 'Duty start (UTC)', 'Check-in (UTC)', 'End (server UTC)', 'Duration (server seconds)', 'Stop (device, unverified UTC)', 'Duration (device, unverified seconds)', 'Duty status', 'Tracking status', 'Last observation (UTC)', 'Accuracy (m)'], ...all.map(row => [row.employeeCode, row.name, row.isDemo, row.dutySessionId, row.startTime, row.checkInTime, row.actualEndTime, row.serverDurationSeconds, row.reportedStopTime, row.reportedDurationSeconds, row.status.duty, row.status.tracking, row.lastSeen, row.accuracy])]); } catch (failure) { setError(String(failure)); } finally { setExporting(false); } }
  return <><div className="page-heading"><div><div className="eyebrow">DAILY ACCOUNTABILITY</div><h1>Duty reports</h1><p>Includes officers without a duty and sessions without check-in.</p></div><button className="button primary" disabled={exporting || !date} onClick={() => void exportAll()}><Download size={16} />{exporting ? 'Exporting every page…' : 'Export CSV'}</button></div><section className="panel"><div className="table-toolbar"><label className="filter-label">Duty start date<input required type="date" value={date} onChange={event => { if (event.target.value) { setDate(event.target.value); setOffset(0); } }} /></label><span className="quiet-label">{timezone} · one row per session</span></div><ErrorNotice message={error || records.error} retry={() => void records.reload()} /><div className="table-wrap"><table><thead><tr><th>Officer</th><th>Duty start</th><th>Check-in</th><th>Server end</th><th>Server duration</th><th>Duty</th><th>Tracking</th></tr></thead><tbody>{records.data?.items.map(row => <tr key={row.fmoId + (row.dutySessionId ?? '')}><td><strong>{row.name}<Demo show={row.isDemo} /></strong><small>{row.employeeCode}</small></td><td>{time(row.startTime, timezone)}</td><td>{time(row.checkInTime, timezone)}</td><td>{time(row.actualEndTime, timezone)}</td><td>{duration(row.serverDurationSeconds)}</td><td><Badge value={row.status.duty} /></td><td><Badge value={row.status.tracking} /></td></tr>)}</tbody></table></div>{!records.data?.items.length && <Empty title={records.busy ? 'Loading report…' : 'No officers for this report'} />}<Pager offset={offset} hasMore={records.data?.hasMore ?? false} onPage={setOffset} busy={records.busy} /><p className="muted" style={{ padding: 20 }}>Dates select duty start in the organization timezone. Server duration includes any offline completion delay; the CSV includes device-reported stop/duration separately as unverified. Current active accounts without a session are shown, not a historical employment roster.</p></section></>;
}
