import { useEffect, useState, type FormEvent } from 'react';
import { api } from '../lib/auth';
import type { Settings as Values } from '../types';
import { Empty, ErrorNotice } from '../components/ui';
export function Settings({ settings, changed }: { settings: Values | null; changed(): void }) {
  const [draft, setDraft] = useState(settings), [dirty, setDirty] = useState(false), [busy, setBusy] = useState(false), [message, setMessage] = useState(''), [error, setError] = useState('');
  useEffect(() => { if (!dirty) setDraft(settings); }, [settings]);
  if (!draft) return <Empty title="Loading organization settings…" />;
  function edit(key: keyof Values, value: string | number) { setDraft(current => current ? { ...current, [key]: value } : current); setDirty(true); setMessage(''); }
  async function save(event: FormEvent) { event.preventDefault(); if (busy) return; setBusy(true); setError(''); try { const result = await api<{ settings: Values }>('/api/settings', 'PUT', draft); setDraft(result.settings); setDirty(false); setMessage('Organization settings saved and audited.'); changed(); } catch (failure) { setError(String(failure)); } finally { setBusy(false); } }
  return <><div className="page-heading"><div><div className="eyebrow">ORGANIZATION CONFIGURATION</div><h1>Settings</h1><p>Duty policies, location frequency and GPS quality.</p></div></div><section className="panel"><form className="form-body" onSubmit={event => void save(event)}><ErrorNotice message={error} />{message && <p role="status" className="muted">{message}</p>}<div className="form-grid"><label>Organization name<input required maxLength={150} value={draft.organizationName} onChange={event => edit('organizationName', event.target.value)} /></label><label>Timezone<input required value={draft.timezone} onChange={event => edit('timezone', event.target.value)} placeholder="Asia/Karachi" /></label>{([['dutyDurationMinutes', 'Duty duration (minutes)', 30, 1440], ['trackingIntervalSeconds', 'Tracking interval (seconds)', 30, 300], ['staleAfterSeconds', 'Stale after (seconds)', 60, 3600], ['offlineAfterSeconds', 'Offline after (seconds)', 120, 86400], ['gpsAccuracyThresholdMeters', 'GPS accuracy threshold (meters)', 5, 1000]] as const).map(([key, label, min, max]) => <label key={key}>{label}<input type="number" required min={min} max={max} value={draft[key]} onChange={event => edit(key, Number(event.target.value))} /></label>)}</div><p className="muted">Offline threshold must exceed stale threshold, which must exceed the tracking interval. Existing duty start/expected-end snapshots do not change. Android refreshes its interval on foreground recovery. Automatic duty-end remains disabled to avoid silent data loss.</p><div className="modal-actions"><button className="button primary" disabled={busy || !dirty}>{busy ? 'Saving…' : 'Save settings'}</button></div></form></section></>;
}
